outline = [
	"introduction",
	"stdlib"
]
[names]
searchbytag = "标签搜索"

[tagnames]
data = ["数据"]
draw = ["绘图"]
format = ["格式"]
gui = ["图形用户界面"]
machine_learning = ["机器学习"]
meta = []
network = ["网络"]
science = ["科学"]
stdlib = ["标准库"]
tool = ["工具"]
visualization = ["可视化"]
wrap = ["库","包裹"]

[tags]
introduction = ["meta"]
develop = ["meta"]
classify = ["meta"]
searchbytag = ["meta"]
stdlib = ["meta"]
cairo = ["draw","visualization"]
colortypes = []
downloads = ["network","stdlib"]
gtk = ["gui"]
markdown = ["format","stdlib"]
pkg = ["stdlib","tool"]
plots = ["data","visualization"]
random = ["data","stdlib"]
toml = ["format","stdlib"]
uuids = ["stdlib"]
unicode = ["stdlib","tool"]
zipfile = ["format"]
