version = ">= 1.3.0"

[giscus]
repo = "JuliaRoadmap/zh"
repo_id = "R_kgDOHQYI2Q"
category_id = "DIC_kwDOHQYI2c4CO2c9"
lang = "zh-CN"

[pages]
lang = "zh"
logo_path = "assets/images/logo.png"
repo_name = "zh"
repo_owner = "JuliaRoadmap"
server_prefix = "/zh"
sort_file = true
throwall = true
title = "Roadmap"
