using Documenter

makedocs(
    sitename = "Julia Roadmap",
    modules = Module[],
    source = "docs",
    build = joinpath(@__DIR__, "public", "docs"),
    format = Documenter.HTML(
        prettyurls = false,
        lang = "zh-CN",
        sidebar_sitename = true,
        edit_link = "master",
        assets = ["assets/giscus.js"],
        repolink = "https://github.com/JuliaRoadmap/zh",
        inventory_version = "1",
    ),
    repo = Documenter.Remotes.GitHub("JuliaRoadmap", "zh"),
    warnonly = true,
    pages = [
        "准备" => [
            "meta/about.md",
            "meta/introduction.md",
            "meta/resources.md",
            "meta/setup_workspace.md",
        ],
        "语言基础" => [
            "basic/setup_environment.md",
            "basic/hello.md",
            "basic/variable_basic.md",
            "basic/int.md",
            "basic/float.md",
            "basic/bool.md",
            "basic/basicio.md",
            "basic/little_types.md",
            "basic/statement.md",
            "basic/loop.md",
            "basic/error.md",
            "basic/range.md",
            "basic/function.md",
            "basic/vector.md",
            "basic/string.md",
            "basic/array.md",
            "basic/dict.md",
            "basic/io.md",
            "basic/scope.md",
            "basic/dev_skills.md",
            "basic/misc.md",
        ],
        "语言进阶" => [
            "advanced/introduction.md",
            "advanced/typesystem.md",
            "advanced/struct.md",
            "advanced/method.md",
            "advanced/module.md",
            "advanced/meta.md",
            "advanced/async.md",
            "advanced/multithreading.md",
            "advanced/else.md",
        ],
        "工作流程" => [
            "workflow/introduction.md",
            "workflow/develop.md",
            "workflow/documentation.md",
            "workflow/stdlib.md",
            "workflow/optimize.md",
            "workflow/resources.md",
        ],
        "专题" => [
            "blog/ecosystem.md",
            "算法" => [
                "blog/algorithms/introduction.md",
                "blog/algorithms/sort.md",
            ],
            "数据与人工智能" => [
                "blog/data_and_ai/introduction.md",
                "blog/data_and_ai/regressor.md",
                "blog/data_and_ai/models.md",
                "blog/data_and_ai/tunedmodel.md",
                "blog/data_and_ai/data.md",
                "blog/data_and_ai/evaluate.md",
            ],
        ],
    ],
)
