[names]
diff = "区别"
know = "了解"
[tagnames]
call = ["调用"]
diff = ["区别"]
error = ["报错"]
fix = ["修复"]
get = ["获取"]
judge = ["判断","估计"]
know = ["知道","知晓","了解"]
transform = ["convert","parse","转化","转换"]

package = ["包"]
