[names]
basic = "算法基础"
search = "搜索"
dp = "动态规划"
string = "字符串相关"
math = "数学相关"
datastructure = "数据结构"
graphalgorithm = "图算法"
geometry = "计算几何"
compression = "压缩算法"
encryption = "数据加密"
numerical = "数值算法"
misc = "杂项"
