outline = [
	"setup_environment",
	"hello",
	"variable_basic",
	"int",
	"float",
	"bool",
	"basicio",
	"little_types",
	"statement",
	"loop",
	"error",
	"range",
	"function",
	"vector",
	"string",
	"array",
	"dict",
	"io",
	"scope",
	"misc",
	"test"
]
