outline = [
	"setup_environment",
	"comment",
	"variable_basic",
	"int",
	"float",
	"bool",
	"print",
	"little_types",
	"statement",
	"loop",
	"error",
	"range",
	"function",
	"vector",
	"string",
	"array",
	"dict",
	"io",
]
