name: Build Docs
on:
  push:
    branches: [master]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[nobuild]'))"
    steps:
      - uses: actions/checkout@v3
      - run: |
          julia -e '
            using Pkg
            Pkg.add(name="DoctreePages")
            using DoctreePages
            github_action()
          '
      # 暂不推送到 github pages
      # - uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: "./public"
      - name: deploy to juliacn docs server
        uses: appleboy/scp-action@master
        with:
          host: juliacn.com
          username: ${{ secrets.MIRROR_SERVER_USERNAME }}
          key: ${{ secrets.MIRROR_SERVER_SSH_KEY }}
          source: "./public/*"
          target: "/gs/roadmap_zh.jl/"
